### ISSUE TITLE
Command option to disable trx output

### ISSUE THREAD

**Issue by Tasteful** [devlooped/dotnet-retest#29]
I trying to use the dotnet-retest in my DevOps Server pipeline, I write the test into trx files directly that I pushing into DevOps Server for the build and that is working and test result is presented in the test-tab.

But, the list of all executed test is bloating the console log for the build and I should like to disable the trx summary output. 

Is there a change that we can add an extra switch in [this if-statement](https://github.com/devlooped/dotnet-retest/blob/e885b0e10db20f1d89dbc1ad2cf7570e8e115cc9/src/dotnet-retest/RetestCommand.cs#L191C1-L202C10) to be able to turn it off? I can do a PR if you think this is a good idea.

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
This is great feedback. I have a fix in place, a new `--no-summary` switch. Shipping it soon. Thanks!
